export const dancers = [
    "Sergiu Gorceag",
    "Corneliu Spînu",
    "Călin Pahomi",
    "Burciu Artur",
    "Andrei Luceac",
    "Mihai Cernalevschi",
    "Victor Vition",
    "Nicu Garbuz",
    "Nicolae Sirghi",
    "Ștefan Secrieru",
    "Alexandr Bezuric",
    "Adriana Munteanu",
    "Daniela Spînu",
    "Carolina Tverdohleb",
    "Victoria Gâscă",
    "Evelina Ustica",
    "Diana Scripnic",
    "Sabina Nichifor",
    "Mihaela Mariș",
    "Victoria Roșca",
    "Cristina Mihai",
    "Marinela Pascari",
];