export const dancers = [
    "Sergiu Gorceag",
    "Corneliu Spînu",
    "Călin Pahomi",
    "Burciu Artur",
    "Andrei Luceac",
    "Mihai Cernalevschi",
    "Victor Vition",
    "Nicu Garbuz",
    "Nicolae Sirghi",
    "Ștefan Secrieru",
    "Maxim Musteață",
    "Adriana Munteanu",
    "Daniela Spînu",
    "Carolina Tverdohleb",
    "Victoria Gâscă",
    "Evelina Ustica",
    "Diana Scripnic",
    "Sabina Nichifor",
    "Arina Romanenco",
    "Victoria Roșca",
    "Cristina Mihai",
    "Marinela Pascari",
];